tasks:
  - init: npm install
    command: |
     export HMR_HOST='gp url 5173'
     npm run dev

ports:
  - port: 5173
    onOpen: open-browser 

vscode:
  extensions:
    - svelte.svelte-vscode

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true